name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --no-audit --no-fund
      
      - name: Test
        run: npm run test:run
      
      - name: Build
        run: npm run build
      
      - name: Create archive
        run: tar -czf mcp-gsheets-${{ github.ref_name }}.tar.gz dist package.json README.md LICENSE
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: mcp-gsheets-${{ github.ref_name }}.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}